version: '3'
 
services:
  hotel:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: on-failure
    ports:
      - "${PORT}:${PORT}"
    container_name: hotel-app
      
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: db
    volumes: 
      - psql:/var/lib/postgresql/data

volumes:
  psql: